Orestis
sopra-fs23-group-03/sopra-fs23-group-03-server pull request #156
Opened 2023-04-17 09:43 UTC by OrestisBollano

Creation of Get /users/{userId}, changes to logout method and all the tests for both of Get /users/{userId} and logout

2023-04-17 21:44 UTC, akkuebler requested changes

2023-04-17 21:44 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/controller/UserController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Imo it would be helpful to keep the comments about what each http status means. like here add the // OK is 200 again.

2023-04-17 21:44 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/controller/UserController.java
> +    @GetMapping("/users/{userId}")
pls update REST table in teams according to the newly implemented calls. We introduced the "done" column for this.

2023-04-17 21:44 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/controller/UserController.java
> +    @ResponseStatus(HttpStatus.OK)
pls add comment here about http code as well

2023-04-17 21:44 UTC, akkuebler commented on src/test/java/ch/uzh/ifi/hase/soprafs23/controller/UserControllerTest.java
>      // TODO: add logout test?
can this be deleted?

2023-04-18 09:04 UTC, wlany requested changes

2023-04-18 09:04 UTC, wlany commented on src/main/java/ch/uzh/ifi/hase/soprafs23/controller/GroupController.java
> +    public GroupGetDTO createGroup(@RequestBody GroupPostDTO groupPostDTO, @RequestParam Long hostId) {
Add the authenticity check
-> check the X-Token header
      -> is there a user with that token?
      -> is the id of the user with that token the same as the hostId?

2023-04-23 17:17 UTC, wlany approved these changes
looks good :D

2023-04-23 17:24 UTC, merged