Tests and sonarcloud cleanup
sopra-fs23-group-03/sopra-fs23-group-03-server pull request #209
Opened 2023-04-29 12:55 UTC by wlany

.

2023-04-29 19:24 UTC, OrestisBollano approved these changes
Very detailed and comprehensive cleanup looks good. :)

2023-04-30 09:51 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/service/GroupService.java
> +    // TODO: why does this exist? it's even tested! but only used where it's tested nowhere else
This was made by me bc it was part of one of my dev tasks. I did it for future use --> thats why it is tested as well.

2023-04-30 09:52 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/service/GroupService.java
> +    // TODO: why does this exist? it's even tested! but only used where it's tested nowhere else
Imo it can stay and we use it for checking whether after allowing for drop outs, there is still at least one guest within the group

2023-04-30 09:53 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/service/GroupService.java
> +    // TODO: why does this exist? it doesn't flush the repo, so it wouldn't work, but it's also never used
that one could go imo if its neverused and never even tested.

2023-04-30 09:55 UTC, akkuebler commented on src/main/java/ch/uzh/ifi/hase/soprafs23/service/UserService.java
> +    // TODO: why does this exist? this is not functionality we are going to implement right?
prbly also my fault as this is a leftover of my invitation logic I guess. Can be deleted

2023-04-30 09:56 UTC, akkuebler requested changes
Thanks for the detailed check Lany! Imo 2/3 of the methods mentioned can be deleted.

2023-04-30 10:51 UTC, akkuebler reviewed
.

2023-04-30 10:52 UTC, akkuebler reviewed
ok

2023-04-30 10:53 UTC, akkuebler approved these changes

2023-04-30 10:53 UTC, merged